#pragma once

// From glfw3.h
#define SLTH_MOUSE_BUTTON_1         0
#define SLTH_MOUSE_BUTTON_2         1
#define SLTH_MOUSE_BUTTON_3         2
#define SLTH_MOUSE_BUTTON_4         3
#define SLTH_MOUSE_BUTTON_5         4
#define SLTH_MOUSE_BUTTON_6         5
#define SLTH_MOUSE_BUTTON_7         6
#define SLTH_MOUSE_BUTTON_8         7
#define SLTH_MOUSE_BUTTON_LAST      SLTH_MOUSE_BUTTON_8
#define SLTH_MOUSE_BUTTON_LEFT      SLTH_MOUSE_BUTTON_1
#define SLTH_MOUSE_BUTTON_RIGHT     SLTH_MOUSE_BUTTON_2
#define SLTH_MOUSE_BUTTON_MIDDLE    SLTH_MOUSE_BUTTON_3